### ISSUE TITLE
Is it possible to model Infinity's face 2 face rolls in icepool?

### ISSUE THREAD

**Issue by alexrecarey** [HighDiceRoller/icepool#100]
I created a python script that calculated the probability of success in [Infinity's face 2 face rolls mechanic](https://infinitythewiki.com/Rolls#Face_to_Face_Rolls) (described below, no need to follow the link), but my naive implementation takes way too long to finish for dice pools over 5 and I was hoping Icepool could run it in a more optimized fashion. I've been diving into the documentation and examples and tried a few things out, but so far I have not had success. 

I think that the issue is that in the `next_step()` function I cannot calculate whether a result is successful or not just by looking at the number of dice that had a particular result, due to Infinity's somewhat unique mechanic.

The mechanic is as follows. The attacker and defender each roll a pool of d20 dice, from 1 to 5. This means the most complex calculation would have 5 attacking dice and 5 defending dice. 

The attacker and the defender each have their own success value. For the die to be a success, it needs to be equal or lower to the success value. However, each successful dice cancels out the all of the opponents dice of equal or lower value. 

For example, if the attacker rolls a ```5, 7, 15``` with a success value of 14 and the defender rolls ```3, 10``` with a success value of 12 the defenders 3 will be cancelled by the attackers 7, and the attackers 5 and 7 will be cancelled by the defenders 10. The defender wins this face 2 face roll with 1 success.

This is further complicated by the existence of critical successes. If either attacker or defender rolls a number equal to their success value that is considered a critical, and they automatically win the roll. The non critical dice are still cancelled normally so you can have x number or critical and y number of successes in a roll. This is importante to calculate damage down the line.

If both players score a critical, the result is a tie, which means 0 successes for each side.

I would like to calculate, for a given number of dice rolled by each side and a given success number for each side, the % chance of all valid results. This means number of successes and critical for each side. So for example, when rolling 3 dice vs 2 dice with a particular success values, the % chance of:

- attacker 3 crits
- attacker 2 crits + 1 success
- attacker 2 crits
- attacker 1 critical + 2 successes
- attacker 1 critical + 1 success
- attacker 1 critical
- attacker 3 successes
- attacker 2 successes
- attacker 1 success
- no successes
- defender 1 success
- defender 2 successes
- defender 1 critical
- defender 1 critical and 1 success
- defender 2 criticals

Is this possible? I don't have access to the other die values when in `next_step()` of an `OutcomeCountEvaluator`.

I've looked at `OutcomeCountGenerator` but I have not seen any examples of it being used and I'm not sure it would be any faster than just iterating brute force through all results? I know there is a lot of optimization that can be done with combinatorics as for a given success value, the dice results are interchangeable (rolling a 1, 2, 3 is the same as 3, 2, 1).

Thank you for the time, I have really been enjoying working with icepool so far! Super fast and well documented.

**Comment by HighDiceRoller** [comment]
Glad to get your message! I've taken a crack at a solution in [this notebook](https://highdiceroller.github.io/icepool/notebooks/lab?path=infinity_universe.ipynb). Let me know if I've interpreted your question correctly.

> Is this possible? I don't have access to the other die values when in `next_state()` of an `OutcomeCountEvaluator`.

The trick here is that you can store whatever information you need about dice that rolled previous outcomes in the `state`. The reason we don't store the entire set of previous outcomes automatically is that the fewer unique states there are, the faster the computation is. Fortunately, in many cases no extra information is needed beyond the partial answer. This includes this case; it's possible to just make the state the 4-tuple `a_crit, a_success, b_crit, b_success`, and then zero out previous successes as we see higher and higher outcomes (or crits).

> I've looked at `OutcomeCountGenerator` but I have not seen any examples of it being used

For the most part I expect users to subclass `OutcomeCountEvaluator`, but use the provided `Pool` (or `Deal` for cards though that API is less stable) as-is for the generator.

**Comment by alexrecarey** [comment]
I'm kind of speechless. Thank you so much for taking the time to code the solution! A scant 40 lines of code, and the results are _instant_ up to crazy amounts of dice. Icepool is insanely powerful.

I'm super curious about the functioning of icepool and the algorithm now. I'll be taking a good look at the source, because even stepping though the execution loop by loop, I'm not 100% sure of how the results are being gathered.

As far as I understand, `outcome` is a result on a die, but it's being used by both player A's success value and player B's success value? I think one `InfinityUniverseEvaluator` is generated for each die, and the final state of each generator is combined together. There is something about the actual algorithm being used that I don't understand. Maybe I should just go read your paper. 😄 

Thanks again for taking the time!

**Comment by HighDiceRoller** [comment]
Glad to help!

> As far as I understand, `outcome` is a result on a die, but it's being used by both player A's success value and player B's success value?

That's right. As far as `next_state` is concerned, it sees:

* How many 1s were rolled by each player.
* How many 2s were rolled by each player.
* ...
* How many 20s were rolled by each player.

At each step it gets to update the `state`, and at the end you get the final result of that roll. The overall solution is equal to executing this sequence of operations on each possible set of rolls and counting the results.

Of course, it would be far too expensive to *actually* enumerate every such possibility. Instead, we can compute the solution to pools of d20s using solutions to pools of d19s (of varying size), which are in turn computed using solutions to pools of d18s, and so on. It's the `OutcomeCountGenerator`s---in this case, the `Pool`s for player A and B---that are instantiated multiple times to represent these "shorter" pools. Then the `Pool`s and `next_state` cooperate to build the solution to the "taller" (more outcomes per die) pools using the solutions to "shorter" pools: the `Pool` knows how to weight the partial solutions and the corresponding `count`s to send to `next_state`, and `next_state` takes care of updating the `state`s as above. All of these partial solutions are memoized inside the single `InfinityUniverseEvaluator` instance, which gets rid of a huge number of redundant computations.

> Maybe I should just go read your paper.

It could help---as reading material, the source code does have the disadvantage that it is supporting a whole bunch of features and syntactic conveniences; any single problem is unlikely to use but a fraction of the code. However, without these extensions, the basic core of the algorithm can be implemented in a mere 15 lines or so.

**Comment by alexrecarey** [comment]
Absolutely beautiful. Thank you for that explanation, I will definitely be checking out the paper as I am very curious now!
