### ISSUE TITLE
Modeling different success values for each player

### ISSUE THREAD

**Issue by alexrecarey** [HighDiceRoller/icepool#101]
I've been tinkering with the InfinityUniverseEvaluator to add in the final rule in the face 2 face roll. For success values larger than 20, the success value is set to 20 and the remainder is actually added to the die result. This makes criticals much more likely if you have a very high success value, as any value 20 or higher is a critical.

I think I am close to the solution, but the code I've written generates the wrong results when the Success Value goes above 20. In this case player A has a SV of 21, but there are no results where player B acheives a Crit. I'm pretty sure I'm doing something wrong!

```
import icepool
from icepool import d20

class InfinityUniverseEvaluator(icepool.OutcomeCountEvaluator):
    def __init__(self, a_sv, b_sv):
        # success values over 20 give a bonus to the die result
        self.a_sv = a_sv if a_sv <= 20 else 20
        self.a_bonus = 0 if a_sv <= 20 else a_sv - 20
        self.b_sv = a_sv if b_sv <= 20 else 20
        self.b_bonus = 0 if b_sv <= 20 else b_sv - 20

    # Note that outcomes are seen in ascending order by default.
    def next_state(self, state, outcome, a_count, b_count):
        # Initial state is all zeros.
        a_crit, a_success, b_crit, b_success = state or (0, 0, 0, 0)

        a_outcome = min(outcome + self.a_bonus, 20)
        b_outcome = min(outcome + self.b_bonus, 20)

        # First, accumulate scores.
        if a_outcome < self.a_sv:
            a_success += a_count
        elif a_outcome == self.a_sv:
            a_crit += a_count
        if b_outcome < self.b_sv:
            b_success += b_count
        elif b_outcome == self.b_sv:
            b_crit += b_count

        # Then, cancel the other side's current and previous successes,
        # which must all have been equal or less than the current outcome.
        # Crits continue to cancel future (higher) successes as well.
        if a_crit or (a_count > 0 and a_outcome <= self.a_sv):
            b_success = 0
        if b_crit or (b_count > 0 and b_outcome <= self.b_sv):
            a_success = 0

        # Finally, cancel all crits if both sides scored any crit.
        if a_crit > 0 and b_crit > 0:
            # Note that successes were already cancelled above.
            # Also, no more outcomes will matter since
            # all remaining outcomes are above SV.
            a_crit = 0
            b_crit = 0
        return a_crit, a_success, b_crit, b_success


print(InfinityUniverseEvaluator(a_sv=21, b_sv=20).evaluate(d20.pool(1), d20.pool(1)))
```

**Comment by HighDiceRoller** [comment]
The reason there are no crits for player B is that there is an error in the assignment to `self.b_sv`. However, there is a more subtle issue, which is that the code relies on the same outcome for each player being seen at the same time in order to ensure that lower outcomes are cancelled by higher outcomes.

In this case, instead of modifying the evaluator, it's easier to modify the pool. Specifically, as you note, the "the remainder is actually added to the die result", with rolls above 20 treated as 20, i.e. a critical. Thus we can simply re-use the *original* `InfinityUniverseEvaluator` and evaluate it using a die modified in this way:

```
from icepool import d20, lowest
print(InfinityUniverseEvaluator(a_sv=20, b_sv=20).evaluate(lowest(d20+1, 20).pool(1), d20.pool(1)))
```

**Comment by alexrecarey** [comment]
Makes a ton of sense. Thanks again for the help!
