### ISSUE TITLE
Consider bundling `icepool` with the JupyterLite distribution

### ISSUE THREAD

**Issue by HighDiceRoller** [HighDiceRoller/icepool#34]
This would save the annoying

```
import piplite
await piplite.install("icepool")
```

at the beginning of each notebook.

Potential issues:

* According to the [example JupyterLite config](https://github.com/jupyterlite/jupyterlite/blob/main/examples/jupyter_lite_config.json), a static version is fetched, which would require manual updating.
  * Unless the URL was constructed dynamically?
  * Or perhaps we could include a static build?
* The documentation [makes it sound like](https://jupyterlite.readthedocs.io/en/latest/configuring.html#adding-pyolite-wheels) this wouldn't actually obviate the lines above? Also, the example notebooks still use piplite to import modules.

So it looks like the main reason to do this is if we want the distribution to use icepool built from HEAD rather than the latest PyPi version.

**Comment by HighDiceRoller** [comment]
I think it's more valuable to have the JupyterLite synced with PyPi, otherwise we may get nasty surprises when we try to `pip install icepool` locally and run the same code as an example notebook.

**Comment by HighDiceRoller** [comment]
Although... bundling it would have the advantage that old versions of the distribution would be runnable as-is, even if the notebooks were using old syntax. I'll give this a try.

**Comment by HighDiceRoller** [comment]
Also I wonder if specifying a specific version in a notebook will fallback to PyPi.

**Comment by HighDiceRoller** [comment]
Got it to build. We'll see if it works as intended.

**Comment by posita** [comment]
My guess is that it doesn't make `icepool` available to notebooks. FWIW, I've been struggling to get something like this working on my end as well, and I don't think it works as anticipated. I still have to `await piplite.install(…)` within each notebook.

**Comment by HighDiceRoller** [comment]
Yeah, the documentation is a bit confusing on that part. I think what happens is that `piplite.install` is still required but it picks up the bundled version in preference to searching PyPi, which at least allows pinning `icepool` (or whatever package) to a specific version. There are some packages that can be imported without going through `piplite` but my guess is that those are either part of the Python standard library or bundled with the underlying Pyodide?
