### ISSUE TITLE
Decide what value to use for infinite max depth / repeat

### ISSUE THREAD

**Issue by HighDiceRoller** [HighDiceRoller/icepool#89]
## Options

* `None` as current.
  * Doesn't read well with `repeat` and the new `depth` (rather than `max_depth`). Unless we rename these to something like `limit`? But I think this is less descriptive.
* `math.inf`
  * mypy doesn't allow floats as literals.
* A new special value, `Unlimited`?

## Should `None` be retained as a synonym?

Pros:

* Easy to use.

Cons:

* Doesn't read well, `None` sounds like zero rather than infinity.

numpy/scipy has precedents in both directions.

**Comment by HighDiceRoller** [comment]
`None` seems fine until further notice.

**Comment by bszonye** [comment]
I'm not sure of the context of this issue, but it seems like the `Ellipsis` object might be semantically appropriate.
